import { Weapon } from '../types/game';

export const WEAPONS: Weapon[] = [
  {
    id: 'spoon',
    name: 'Cereal Spoon',
    damage: 10,
    attackSpeed: 1,
    range: 80,
    knockback: 10,
    description: 'A trusty breakfast spoon. Perfect for milk lovers.',
    color: '#C0C0C0',
    emoji: '🥄'
    // No price - starting weapon
  },
  {
    id: 'whisk',
    name: 'Turbo Whisk',
    damage: 8,
    attackSpeed: 2,
    range: 60,
    knockback: 8,
    description: 'Whips enemies into a frenzy!',
    color: '#FFD700',
    emoji: '🥄',
    price: 75
  },
  {
    id: 'bottle',
    name: 'Empty Milk Bottle',
    damage: 15,
    attackSpeed: 0.7,
    range: 120,
    knockback: 35,
    description: 'Heavy glass bottle. Bonk!',
    color: '#FFFFFF',
    emoji: '🍼',
    price: 100
  },
  {
    id: 'cookie',
    name: 'Boomerang Cookie',
    damage: 12,
    attackSpeed: 1.2,
    range: 150,
    knockback: 15,
    description: 'Comes back for double damage!',
    color: '#D2691E',
    emoji: '🍪',
    price: 125
  },
  {
    id: 'straw',
    name: 'Explosive Straw',
    damage: 20,
    attackSpeed: 0.5,
    range: 200,
    knockback: 25,
    description: 'Shoots milk projectiles!',
    color: '#FF69B4',
    emoji: '🥤',
    price: 150
  },
  {
    id: 'cheese',
    name: 'Cheese Wheel',
    damage: 25,
    attackSpeed: 0.4,
    range: 100,
    knockback: 50,
    description: 'Roll over your enemies!',
    color: '#FFD700',
    emoji: '🧀',
    price: 175
  },
  {
    id: 'icecream',
    name: 'Ice Cream Cone',
    damage: 18,
    attackSpeed: 0.8,
    range: 140,
    knockback: 20,
    description: 'Freezes enemies in their tracks!',
    color: '#FFC0CB',
    emoji: '🍦',
    price: 150
  },
  {
    id: 'yogurt',
    name: 'Yogurt Tsunami',
    damage: 30,
    attackSpeed: 0.3,
    range: 180,
    knockback: 45,
    description: 'Overwhelm with probiotics!',
    color: '#FFB6C1',
    emoji: '🥛',
    price: 200
  },
  {
    id: 'butter',
    name: 'Butter Blade',
    damage: 22,
    attackSpeed: 0.9,
    range: 90,
    knockback: 18,
    description: 'Smooth and deadly!',
    color: '#FFDB58',
    emoji: '🧈',
    price: 175
  },
  {
    id: 'milkshake',
    name: 'Mega Milkshake',
    damage: 35,
    attackSpeed: 0.6,
    range: 160,
    knockback: 40,
    description: 'The ultimate dairy weapon!',
    color: '#FF1493',
    emoji: '🥤',
    price: 250
  },
  {
    id: 'croissant',
    name: 'Croissant Boomerang',
    damage: 14,
    attackSpeed: 1.5,
    range: 130,
    knockback: 12,
    description: 'French pastry of pain!',
    color: '#F4A460',
    emoji: '🥐',
    price: 125
  },
  {
    id: 'cupcake',
    name: 'Cupcake Cannon',
    damage: 16,
    attackSpeed: 1.3,
    range: 110,
    knockback: 22,
    description: 'Sweet but deadly!',
    color: '#FFB6D9',
    emoji: '🧁',
    price: 150
  },
  {
    id: 'donut',
    name: 'Donut Discus',
    damage: 19,
    attackSpeed: 1.1,
    range: 140,
    knockback: 16,
    description: 'Glazed and confused!',
    color: '#FFE4B5',
    emoji: '🍩',
    price: 160
  },
  {
    id: 'pizza',
    name: 'Pizza Slice Shuriken',
    damage: 21,
    attackSpeed: 0.85,
    range: 125,
    knockback: 28,
    description: 'Cheesy destruction!',
    color: '#FF6347',
    emoji: '🍕',
    price: 175
  },
  {
    id: 'egg',
    name: 'Egg Grenade',
    damage: 28,
    attackSpeed: 0.65,
    range: 95,
    knockback: 42,
    description: 'Explosive breakfast!',
    color: '#FFFACD',
    emoji: '🥚',
    price: 200
  },
  {
    id: 'bacon',
    name: 'Bacon Whip',
    damage: 17,
    attackSpeed: 1.4,
    range: 105,
    knockback: 14,
    description: 'Crispy and devastating!',
    color: '#D2691E',
    emoji: '🥓',
    price: 150
  },
  {
    id: 'pie',
    name: 'Cream Pie Launcher',
    damage: 24,
    attackSpeed: 0.75,
    range: 155,
    knockback: 32,
    description: 'Slapstick warfare!',
    color: '#FFF8DC',
    emoji: '🥧',
    price: 185
  },
  {
    id: 'cake',
    name: 'Birthday Cake Bomb',
    damage: 32,
    attackSpeed: 0.55,
    range: 135,
    knockback: 48,
    description: 'Celebrate with explosions!',
    color: '#FFE4E1',
    emoji: '🎂',
    price: 225
  },
  {
    id: 'lollipop',
    name: 'Giant Lollipop',
    damage: 13,
    attackSpeed: 1.6,
    range: 85,
    knockback: 10,
    description: 'Sticky situation!',
    color: '#FF69B4',
    emoji: '🍭',
    price: 110
  },
  {
    id: 'candy',
    name: 'Candy Cane Sword',
    damage: 20,
    attackSpeed: 1.0,
    range: 100,
    knockback: 24,
    description: 'Minty fresh damage!',
    color: '#FF0000',
    emoji: '🍬',
    price: 165
  },
  {
    id: 'pancake',
    name: 'Pancake Stack',
    damage: 26,
    attackSpeed: 0.7,
    range: 115,
    knockback: 38,
    description: 'Stacks on stacks!',
    color: '#FFE4B2',
    emoji: '🥞',
    price: 190
  },
  {
    id: 'waffle',
    name: 'Waffle Iron',
    damage: 29,
    attackSpeed: 0.6,
    range: 105,
    knockback: 44,
    description: 'Press your enemies!',
    color: '#F0E68C',
    emoji: '🧇',
    price: 210
  },
  {
    id: 'pretzel',
    name: 'Pretzel Shuriken',
    damage: 23,
    attackSpeed: 0.95,
    range: 145,
    knockback: 20,
    description: 'Twisted and salty!',
    color: '#D2B48C',
    emoji: '🥨',
    price: 180
  },
  {
    id: 'baguette',
    name: 'Legendary Baguette',
    damage: 40,
    attackSpeed: 0.5,
    range: 175,
    knockback: 60,
    description: 'The ultimate bread weapon!',
    color: '#DEB887',
    emoji: '🥖',
    price: 300
  },
  {
    id: 'burrito',
    name: 'Burrito Bazooka',
    damage: 38,
    attackSpeed: 0.45,
    range: 190,
    knockback: 55,
    description: 'Wrapped destruction!',
    color: '#CD853F',
    emoji: '🌯',
    price: 275
  },
  {
    id: 'banana',
    name: 'Banana Gun',
    damage: 90,
    attackSpeed: 0.25,
    range: 75,
    knockback: 80,
    description: 'Extreme power, but very slow!',
    color: '#FFFF00',
    emoji: '🍌',
    price: 350
  },
  {
    id: 'nugget',
    name: 'Poop Nugget',
    damage: 29,
attackSpeed: 0.6,
range: 120,
knockback: 35,
    description: 'throw small craps at your enemies',
    color: '#964B00',
    emoji: '💩',
    price: 120,
      },
  {id: 'slimeball',
   name: 'Slimeball',
   damage:5,
   attackSpeed: 3.0,
   range: 150,
   knockback: 10,
   description: 'practally no damage but insane speed',
   color: '#90EE90',
   emoji: '🟢',
   price: 100,
  }
  ]